name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: us-east-1

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --cov=lambda_code --cov-report=xml --cov-report=html
        
    - name: Check test coverage
      run: |
        coverage report --fail-under=80
        
    - name: Terraform validation
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
        terraform fmt -check
        terraform init -backend=false
        terraform validate
        
    - name: Security scan
      run: |
        pip install bandit
        bandit -r lambda_code/ --severity-level medium
        
    - name: Generate test report
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ Unit tests passed" >> $GITHUB_STEP_SUMMARY  
        echo "✅ Security scan completed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Terraform validation passed" >> $GITHUB_STEP_SUMMARY
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: htmlcov/